apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: react-deployment 
spec: 
  selector: 
    matchLabels: 
      app: react 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: react 
    spec: 
      containers: 
      - name: react 
        image: push1697/circunetics-research-frontend
        ports: 
        - containerPort: 80 
